apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-shared
  namespace: kafka-clickhouse
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: kafka-clickhouse
data: {}
