apiVersion: v1
kind: Namespace
metadata:
  name: kafka-clickhouse
  labels:
    app.kubernetes.io/name: kafka-clickhouse
    app.kubernetes.io/part-of: kafka-clickhouse
    app.kubernetes.io/managed-by: kustomize
  annotations:
    owner: kafka-clickhouse
    environment: local
